// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pljxbjohjlvmrxxnzghg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsanhiam9oamx2bXJ4eG56Z2hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg1MDYyNDksImV4cCI6MjA5NDA4MjI0OX0.pB5VLTyZ5_oIbFlr8GR697MszmQxfXQzQ7XX9CB-VKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});